version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: polar-builder-backend
    restart: unless-stopped
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=${SECRET_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - S3_REGION=${S3_REGION}
    volumes:
      - ./backend/src/database.db:/app/src/database.db
      - ./logs:/app/logs
    ports:
      - "5000:5000"
    networks:
      - polar-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=${VITE_API_BASE_URL}
    container_name: polar-builder-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    networks:
      - polar-network
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    container_name: polar-builder-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
      - ./logs/nginx:/var/log/nginx
    networks:
      - polar-network
    depends_on:
      - frontend
      - backend

networks:
  polar-network:
    driver: bridge

volumes:
  database:
  logs:

